version: '3.3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9678:9678"
    depends_on:
      - PostgreSQL
    environment:
      - DBHOST=PostgreSQL
      - DBUSER=postgres
      - DBPASSWORD=postgres
    networks:
      - default

  PostgreSQL:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=127.0.0.1
    volumes:
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - default